### PR TITLE
README.md (kor)

### PR DESCRIPTION
**Pull request by kty4119**
Korean developers also added Hangul to existing README documents to make them easier to understand.

### CODE REVIEW

**Comment by kty4119** [comment]
Hi,
Thank you for your opinion. I will soon create a README-kor.md file as you say and pull requests. And I want to make a guideline about the stone you told me about last time. But I don't know what stone means. Can you tell me what a stone is?

**Comment by Alex1304** [comment]
Huh, when I said *"Of course I am open to contributions, there is no guidelines set in stone yet"*, I just mean that I haven't defined precise guidelines that one should follow in order to contribute to the project. *Set something in stone* is just an english expression that means *define something*.
This is entirely up to me to decide on that, for now I don't feel it's needed, but if it happens to be necessary I can create them in the future.

**Comment by kty4119** [comment]
I have now created a README.md file and modified it again. I hope this file will help. I'll look at the project and think about what I need. Thank you.

**Comment by Alex1304** [comment]
Oh my... uhh, I think you did way too much. You were supposed to just create a Korean version of README, which you did fine, however I didn't want the *whole* project to be translated. You literally copypasted the whole code just to translate the tiny bits of javadoc here and there. This will be hell to maintain, as any modification of the code or the project structure will require to update the Korean part. Also, the code that is compiled and running in the end will be the same. If you want a 100% korean version of the project, you can keep it in your fork, but that's not something I want PR.

So, yes I can accept your changes for the README, because I think having translated *documentation* is legitimate, but translated *code* isn't. I suggest you to push a commit that reverts the project completely as it was before, with just the README-kor.md added, nothing else. Don't forget to revert the original README.md as well

**Comment by kty4119** [comment]
I'm sorry. I didn't even think about it because it was my first time making a contribution. After committing to the original state again, I will add README-kor.md file and upload it again. Once again, I'm so sorry.

**Comment by Alex1304** [comment]
No worries. Just make sure not to make more changes than respository owners request, that way you won't waste your time making unnecessary changes. Now it's much better, thanks.

**Pull request merged**
